package test;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;



public class Test2 {
	public static void main(String[] args)throws ParseException {
		/*test2();*/
		String base64str ="xxxx";
		String  str=new String("\"data:image/jpg;base64,"+base64str+"\"");
		System.out.println(str);
	}
	
	
	public static void test() throws ParseException{
		SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMM");
		Date parse = dateFormat.parse("201608");
		SimpleDateFormat dateFormat2 = new SimpleDateFormat("yyyy-MM");
		String format = dateFormat2.format(parse);
		System.out.println(format);
	}
	
	public static void test1(){
		String a="[ww][77]xxx";
		String[] split = a.split("]");
		System.out.println(split[2]);
		/*for (String string : split) {
			System.out.println(string);
		}*/
	}
	
	public static void test2(){
		double parseDouble = Double.parseDouble("15.04");
		double parseDouble1 = Double.parseDouble("15.04");
		double a= 0d;
		System.out.println(parseDouble+a+parseDouble1);
	}
	
	public static void test3(){
		String base64 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEU"
				+ "gAAAfkAAAFoCAYAAABUjIICAAAPIElEQVR4Xu3VAQ0AAAgCQelf"
				+ "2h6/swGHGztHgAABAgQIJAWWTCUUAQIECBAgcEbeExAgQIAAgaiA"
				+ "kY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQ"
				+ "CAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQI"
				+ "ECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QI"
				+ "AAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeD"
				+ "xAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgIC"
				+ "R9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQ"
				+ "IECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4"
				+ "sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAg"
				+ "EBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfo"
				+ "AAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgS"
				+ "MvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgA"
				+ "ABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIEC"
				+ "BAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQI"
				+ "EDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgS"
				+ "MvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8H"
				+ "CBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIEC"
				+ "BAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQF"
				+ "jHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYs"
				+ "AgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk"
				+ "/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8W"
				+ "KxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAA"
				+ "AQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIG"
				+ "Hk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKx"
				+ "YBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMv"
				+ "B8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAV"
				+ "MDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFix"
				+ ""
				+ "SJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBA"
				+ "gICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AA"
				+ "QIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGP"
				+ "lqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIE"
				+ "DDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAA"
				+ "QJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sVi"
				+ "wABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxA"
				+ "gQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOS"
				+ "jxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAAB"
				+ "I+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgE"
				+ "BUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIE"
				+ "CBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AA"
				+ "QIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGP"
				+ "lqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIE"
				+ "DDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAA"
				+ "QJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sVi"
				+ "wABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeD"
				+ "xAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqY"
				+ "OSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAg"
				+ "AABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIEC"
				+ ""
				+ "BAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0W"
				+ "LEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg"
				+ "5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJ"
				+ "GPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfoAA"
				+ "AQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAkY8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgSMvB8gQIAAAQJRASMfLVYsAgQIECBg5P0AAQIECBCIChj5aLFiESBAgAABI+8HCBAgQIBAVMDIR4sViwABAgQIGHk/QIAAAQIEogJGPlqsWAQIECBAwMj7AQIECBAgEBUw8tFixSJAgAABAkbeDxAgQIAAgaiAk"
				+ "Y8WKxYBAgQIEDDyfoAAAQIECEQFjHy0WLEIECBAgICR9wMECBAgQCAqYOSjxYpFgAABAgQear0BaUNqatQAAAAASUVORK5CYII=";
		
	}
	
	 
}
